// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: monitor/monitor.proto

package remote_system_monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The message containing CPU and RAM stats.
type SystemMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"` // CPU usage percentage
	RamPercent    float64                `protobuf:"fixed64,2,opt,name=ram_percent,json=ramPercent,proto3" json:"ram_percent,omitempty"` // RAM usage percentage
	RamTotal      uint64                 `protobuf:"varint,3,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`        // Total RAM in bytes
	RamUsed       uint64                 `protobuf:"varint,4,opt,name=ram_used,json=ramUsed,proto3" json:"ram_used,omitempty"`           // Used RAM in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_monitor_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_monitor_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *SystemMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetRamPercent() float64 {
	if x != nil {
		return x.RamPercent
	}
	return 0
}

func (x *SystemMetrics) GetRamTotal() uint64 {
	if x != nil {
		return x.RamTotal
	}
	return 0
}

func (x *SystemMetrics) GetRamUsed() uint64 {
	if x != nil {
		return x.RamUsed
	}
	return 0
}

// Empty message for the request (could be extended for filters).
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_monitor_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_monitor_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_monitor_monitor_proto_rawDescGZIP(), []int{1}
}

var File_monitor_monitor_proto protoreflect.FileDescriptor

const file_monitor_monitor_proto_rawDesc = "" +
	"\n" +
	"\x15monitor/monitor.proto\x12\amonitor\"\x89\x01\n" +
	"\rSystemMetrics\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vram_percent\x18\x02 \x01(\x01R\n" +
	"ramPercent\x12\x1b\n" +
	"\tram_total\x18\x03 \x01(\x04R\bramTotal\x12\x19\n" +
	"\bram_used\x18\x04 \x01(\x04R\aramUsed\"\x10\n" +
	"\x0eMetricsRequest2T\n" +
	"\x0eMonitorService\x12B\n" +
	"\rStreamMetrics\x12\x17.monitor.MetricsRequest\x1a\x16.monitor.SystemMetrics0\x01B+Z)github.com/Apolo151/remote_system_monitorb\x06proto3"

var (
	file_monitor_monitor_proto_rawDescOnce sync.Once
	file_monitor_monitor_proto_rawDescData []byte
)

func file_monitor_monitor_proto_rawDescGZIP() []byte {
	file_monitor_monitor_proto_rawDescOnce.Do(func() {
		file_monitor_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_monitor_monitor_proto_rawDesc), len(file_monitor_monitor_proto_rawDesc)))
	})
	return file_monitor_monitor_proto_rawDescData
}

var file_monitor_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_monitor_monitor_proto_goTypes = []any{
	(*SystemMetrics)(nil),  // 0: monitor.SystemMetrics
	(*MetricsRequest)(nil), // 1: monitor.MetricsRequest
}
var file_monitor_monitor_proto_depIdxs = []int32{
	1, // 0: monitor.MonitorService.StreamMetrics:input_type -> monitor.MetricsRequest
	0, // 1: monitor.MonitorService.StreamMetrics:output_type -> monitor.SystemMetrics
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_monitor_monitor_proto_init() }
func file_monitor_monitor_proto_init() {
	if File_monitor_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_monitor_monitor_proto_rawDesc), len(file_monitor_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_monitor_monitor_proto_goTypes,
		DependencyIndexes: file_monitor_monitor_proto_depIdxs,
		MessageInfos:      file_monitor_monitor_proto_msgTypes,
	}.Build()
	File_monitor_monitor_proto = out.File
	file_monitor_monitor_proto_goTypes = nil
	file_monitor_monitor_proto_depIdxs = nil
}
